language: go

sudo: required

os:
- linux

go:
- "1.11.x"
- "1.12.x"
- stable

services:
  - docker

addons:
  apt:
    packages:
    - openjdk-9-jre-headless

install:
- go get -u github.com/mgechev/revive
- sudo curl -o /usr/local/lib/antlr-4.7.2-complete.jar https://www.antlr.org/download/antlr-4.7.2-complete.jar
- export CLASSPATH=".:/usr/local/lib/antlr-4.7.2-complete.jar:$CLASSPATH"
- mkdir $HOME/travis-bin
- echo -e '#!/bin/bash\njava -jar /usr/local/lib/antlr-4.7.2-complete.jar "$@"' > $HOME/travis-bin/antlr
- echo -e '#!/bin/bash\njava org.antlr.v4.gui.TestRig "$@"' > $HOME/travis-bin/grun
- chmod +x $HOME/travis-bin/*
- export PATH=$PATH:$HOME/travis-bin
- export GO111MODULE=on
- git reset --hard

stages:
- lint
- compile
- test
- e2e
- bench

jobs:
  include:
  - stage: lint
    go: stable
    script:
    - make vet
    - make lint
    - make fmt
    - git diff
    - if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi
  - stage: compile
    go: stable
    script:
    - make generate
    - make compile
  - stage: test
    script:
    - make cover
  - stage: e2e
    go: stable
    before_script:
    - docker pull montferret/lab:0.2
    script:
    - docker run -v .:/data -e FERRET_LAB_WAIT=http://127.0.0.1:9222/json/version -e FERRET_LAB_RUNTIME=bin:///data/bin/ferret -e FERRET_LAB_FILES=file:///data/e2e/tests -e FERRET_LAB_DIR=/data/e2e/pages/dynamic:8080@dynamic -e FERRET_LAB_DIR=/data/e2e/pages/static:8081@static montferret/lab:0.2
    after_script:
    - docker stop $(docker ps -q)
  - stage: bench
    go: stable
    script:
    - make bench
